"""Initial migration

Revision ID: 11b584356c38
Revises: 
Create Date: 2025-04-01 22:14:27.368146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b584356c38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)

    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_superheroes_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_superheroes_name'))

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_name'))

    # ### end Alembic commands ###
